# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: financialmanagement
services:
  postgresql:
    image: postgres:16.4
    # volumes:
    #   - ~/volumes/jhipster/financialManagement/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=financialManagement
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - minha-rede

  # Aplicação Spring Boot
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/financialManagement
      SPRING_DATASOURCE_USERNAME: financialManagement
      SPRING_DATASOURCE_PASSWORD: 
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    networks:
      - minha-rede
networks:
  minha-rede:
    driver: bridge
